### ISSUE TITLE
asyncio:ERROR Unclosed connection

### ISSUE THREAD

**Issue by sergeief** [thumbor/thumbor-aws#113]
Thank you for `thumbor-aws`. We were able to successfully serve images from S3 using this library, but discovered a side-effect is that we're seeing a lot of errors like the following:

```
2023-02-17 03:44:54 asyncio:ERROR Unclosed connection
client_connection: Connection<ConnectionKey(host='s3.amazonaws.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
2023-02-17 03:45:12 asyncio:ERROR Unclosed connection
client_connection: Connection<ConnectionKey(host='s3.amazonaws.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=None)>
```

This looks like connections to S3 aren't closed nor reused, any idea what would be the best way to debug or resolve?

**Comment by duffn** [comment]
This is still valid.

**Comment by duffn** [comment]
This is still valid.

**Comment by aekoroglu** [comment]
Still valid

**Comment by Tenzer** [comment]
@guilhermef I just tried to upgrade from thumbor-aws 0.8.0 to 0.9.0 (0.8.1 doesn't seem to ever have been made available in PyPI), and I am hitting the following error:

```
2025-08-26 08:08:38 thumbor:ERROR [BaseHander.execute_image_operations] AWS_NORMALIZER
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/thumbor/handlers/__init__.py", line 145, in execute_image_operations
    result = await self.context.modules.result_storage.get()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/thumbor_aws/result_storage.py", line 168, in get
    file_abspath = normalize_path(self.context, self.prefix, path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/thumbor_aws/utils.py", line 9, in normalize_path
    new_path = context.config.AWS_NORMALIZER(path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/derpconf/config.py", line 225, in __getattr__
    raise AttributeError(name)
AttributeError: AWS_NORMALIZER
```

I'm guessing that comes from https://github.com/thumbor/thumbor-aws/pull/243.

I haven't configured any value for `AWS_NORMALIZER`, should the default value not work?

**Comment by guilhermef** [comment]
Hi @Tenzer , the session should be re-used: https://github.com/thumbor/thumbor-aws/blob/main/thumbor_aws/s3_client.py#L86

**Comment by guilhermef** [comment]
You're right, we need to change the loader to reuse it.
We can switch to store the whole client, instead of the session, it will also work for the loader
