### ISSUE TITLE
TC_AWS_LOADER_BUCKET = ''  not setting bucket from request URL

### ISSUE THREAD

**Issue by bschaefer99** [thumbor/thumbor-aws#18]
Per the tc-aws compatibility section of the docs:
```## S3 bucket for Loader. If given, source urls are interpreted as keys within
## this bucket. If not given, source urls are expected to containthe bucket
## name, such as 's3-bucket/keypath'.
## Defaults to: ''
```
I have this value un-set. I am requesting the following URL:
`/redactedhash=/96x96/one_of_my_s3_buckets/some_image.jpeg`

and i am getting the following error in the thumbor error output:
```
2022-04-24 19:02:13 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/thumbor/handlers/__init__.py", line 212, in get_image
    result = await self._fetch(self.context.request.image_url)
  File "/usr/local/lib/python3.7/dist-packages/thumbor/handlers/__init__.py", line 806, in _fetch
    self.context, url
  File "/usr/local/lib/python3.7/dist-packages/thumbor_aws/loader.py", line 85, in load
    norm_path, expiration=None
  File "/usr/local/lib/python3.7/dist-packages/thumbor_aws/s3_client.py", line 154, in get_data
    Bucket=self.bucket_name, Key=path
  File "/usr/local/lib/python3.7/dist-packages/aiobotocore/client.py", line 199, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.7/dist-packages/aiobotocore/client.py", line 247, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/usr/local/lib/python3.7/dist-packages/aiobotocore/client.py", line 279, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/usr/local/lib/python3.7/dist-packages/aiobotocore/hooks.py", line 29, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/botocore/handlers.py", line 243, in validate_bucket_name
    raise ParamValidationError(report=error_msg)
botocore.exceptions.ParamValidationError: Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"

2022-04-24 19:02:13 thumbor:ERROR [BaseHandler] get_image failed for url `one_of_my_s3_buckets/some_image.jpeg`. error: `Parameter validation failed:
Invalid bucket name "": Bucket name must match the regex "^[a-zA-Z0-9.\-_]{1,255}$" or be an ARN matching the regex "^arn:(aws).*:(s3|s3-object-lambda):[a-z\-0-9]*:[0-9]{12}:accesspoint[/:][a-zA-Z0-9\-.]{1,63}$|^arn:(aws).*:s3-outposts:[a-z\-0-9]+:[0-9]{12}:outpost[/:][a-zA-Z0-9\-]{1,63}[/:]accesspoint[/:][a-zA-Z0-9\-]{1,63}$"`
2022-04-24 19:02:13 tornado.access:ERROR 500 GET /redactedhash=/96x96/one_of_my_s3_buckets/some_image.jpeg (10.0.10.206) 118.34ms
```

**Comment by guilhermef** [comment]
@bschaefer99 you're right, we're always using the bucket name from the config, instead of extracting it from the first part of the path.
I'll try to change it this week.

**Comment by guilhermef** [comment]
Released on: https://github.com/thumbor/thumbor-aws/releases/tag/0.4.2

**Comment by bschaefer99** [comment]
Confirmed! Our tc_aws setup is now functioning as intended. 
Cheers team!
