### ISSUE TITLE
ResultStorage upload failure should not break the process

### ISSUE THREAD

**Issue by ook** [thumbor/thumbor-aws#58]
Let's build a setup: thumbor 7.0.10 + thumbor-aws 0.4.3 + a minio instance.
Minio storage is full, so the ResultStorage.put currently trigger an error:

```
2022-08-08 16:17:23 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 122, in upload
    response = await client.put_object(**settings)
  File "/usr/local/lib/python3.10/site-packages/aiobotocore/client.py", line 265, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/tornado/web.py", line 1713, in _execute
    result = await result
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/imaging.py", line 119, in get
    return await self.check_image(kw)
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/imaging.py", line 116, in check_image
    return await self.execute_image_operations()
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 203, in execute_image_operations
    await self.get_image()
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 301, in get_image
    await self.after_transform()
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 346, in after_transform
    await self.finish_request()
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 579, in finish_request
    await self._store_results(result_storage, metrics, results)
  File "/usr/local/lib/python3.10/site-packages/thumbor/handlers/__init__.py", line 660, in _store_results
    await result_storage.put(results)
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/result_storage.py", line 141, in put
    response = await self.upload(
  File "/usr/local/lib/python3.10/site-packages/thumbor_aws/s3_client.py", line 126, in upload
    raise RuntimeError(msg)  # pylint: disable=raise-missing-from
RuntimeError: Unable to upload image to /rs/bdehnPEqltumHiGwGNindoOr_xM=/516x516/https://files.example.com/uploaders/23779347/illustration-file/7409c4b2-0024-4c25-9759-3671e33c2bca/untitled.153.jpg: An error occurred (XMinioStorageFull) when calling the PutObject operation: Storage backend has reached its minimum free disk threshold. Please delete a few objects to proceed. (<class 'botocore.exceptions.ClientError'>)

```
At this level, the image got processed.
Currently thumbor_aws raise and break totally the request (500)

I suggest to log the error, but return the response image to the upstream server: no reason to break the whole system because we can no longer cache our work.

**Comment by ook** [comment]
I guess I'll propose a PR
