### ISSUE TITLE
I need help, I can't properly process pictures from S3.

### ISSUE THREAD

**Issue by Anbool** [thumbor/thumbor-aws#6]
First of all, I'm sorry, I don't understand English, I usually use Google translate, if I didn't express my question clearly, please understand, thank you!
I'm using an object storage compatible with AWS S3 protocol, when I'm done configuring Thumbor, try to run the image fetched from S3, Thumbor got a 500 error and I need help.

### This is my config file

```yaml
LOADER = 'thumbor.loaders.http_loader'
STORAGE = 'thumbor_aws.storage'
RESULT_STORAGE = 'thumbor_aws.result_storage'
```

```yaml
################################# AWS Storage ##################################
AWS_STORAGE_REGION_NAME = 'ap-beijing'
AWS_STORAGE_BUCKET_NAME = 'img'
AWS_STORAGE_S3_SECRET_ACCESS_KEY = 'XXXXXXXXX'
AWS_STORAGE_S3_ACCESS_KEY_ID = 'XXXXXXXXX'
AWS_STORAGE_S3_ENDPOINT_URL = 'https://cos.ap-beijing.myqcloud.com'
AWS_STORAGE_ROOT_PATH = '/storage'
AWS_STORAGE_S3_ACL = None
AWS_DEFAULT_LOCATION = 'https://img.cos.ap-beijing.myqcloud.com'

################################################################################


############################## AWS Result Storage ##############################
AWS_RESULT_STORAGE_REGION_NAME = 'ap-beijing'
AWS_RESULT_STORAGE_BUCKET_NAME = 'img'
AWS_RESULT_STORAGE_S3_SECRET_ACCESS_KEY = 'XXXXXXXX'
AWS_RESULT_STORAGE_S3_ACCESS_KEY_ID = 'XXXXXX'
AWS_RESULT_STORAGE_S3_ENDPOINT_URL = 'https://cos.ap-beijing.myqcloud.com'
AWS_RESULT_STORAGE_ROOT_PATH = '/result-storage'
AWS_RESULT_STORAGE_S3_ACL = None

################################################################################
```

### My environment configuration

```yaml
thumbor        7.0.6
thumbor-aws    0.4.0
S3             private read and write
```

### Access

```shell
http://127.0.0.1:8689/unsafe/20221/a78a8a02-6c94-452e-9322-62824c458acd.jpg
```

### Error

```python
2022-02-18 03:14:09 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 195, in get_image
    result = await self._fetch(self.context.request.image_url)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 732, in _fetch
    loader_result = await self.context.modules.loader.load(self.context, url)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/loaders/http_loader.py", line 191, in load
    response = await client.fetch(req, raise_error=True)
TimeoutError: [Errno 110] Connection timed out

2022-02-18 03:14:09 thumbor:ERROR [BaseHandler] get_image failed for url `20221/a78a8a02-6c94-452e-9322-62824c458acd.jpg`. error: `[Errno 110] Connection timed out`
2022-02-18 03:14:09 tornado.access:ERROR 500 GET /unsafe/20221/a78a8a02-6c94-452e-9322-62824c458acd.jpg (127.0.0.1) 3231.83ms
```

### Access

```shell
http://127.0.0.1:8689/unsafe/https://www.baidu.com/img/PC_880906d2a4ad95f5fafb2e540c5cdad7.png
```

### Error

```python
2022-02-18 03:12:18 thumbor:ERROR [BaseHander.finish_request] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 514, in finish_request
    result = await self.context.thread_pool.queue(
  File "/usr/local/lib/python3.9/dist-packages/thumbor/threadpool.py", line 53, in queue
    return await self._execute_in_foreground(operation, *args)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/threadpool.py", line 45, in _execute_in_foreground
    return operation(*args)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 428, in _load_results
    image_extension, content_type = self.define_image_type(context, None)
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 393, in define_image_type
    elif self.can_auto_convert_png_to_jpg():
  File "/usr/local/lib/python3.9/dist-packages/thumbor/handlers/__init__.py", line 372, in can_auto_convert_png_to_jpg
    return self.context.request.engine.can_auto_convert_png_to_jpg()
  File "/usr/local/lib/python3.9/dist-packages/thumbor/engines/__init__.py", line 398, in can_auto_convert_png_to_jpg
    can_convert = self.extension == ".png" and not self.has_transparency()
  File "/usr/local/lib/python3.9/dist-packages/thumbor_vips_engine/engine.py", line 151, in has_transparency
    raise NotImplementedError()
NotImplementedError
2022-02-18 03:12:18 thumbor:WARNING Error while trying to fetch the image: 
2022-02-18 03:12:18 tornado.access:ERROR 500 GET /unsafe/https://www.baidu.com/img/PC_880906d2a4ad95f5fafb2e540c5cdad7.png (127.0.0.1) 329.15ms
```

I think Thumbor's configuration on AWS S3 is very simple, but I have these problems, I try to solve them and find that nothing works, I would like to get help from the developers, I would appreciate any reply.
I have been using Thumbor 6.0 for the past two years, and I have to say, Thumbor is an excellent work!

**Comment by heynemann** [comment]
Wait you are using thumbor vips engine? It's not ready, that's why you are getting a NotImplementedError...

**Comment by heynemann** [comment]
About the `TimeoutError: [Errno 110] Connection timed out` probably some network error between your computer and the actual file. Hard to help without understanding your use case better.

**Comment by heynemann** [comment]
BTW your english is fine :)

**Comment by Anbool** [comment]
> Wait you are using thumbor vips engine? It's not ready, that's why you are getting a NotImplementedError...

Yes, I use thumbor vips engine, but I got so many bugs that I had to stop using thumbor vips engine.
I use thumbor-aws to load images from http, this problem has been solved so far, I use thumbor-aws to transfer images from the intranet, there should be no problems with the network, thank you for your reply.
